server:
  port: 9041

spring:
  application:
    name: order-query-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  elasticsearch:
    rest:
      uris: http://localhost:9200
  kafka:
    bootstrap-servers: localhost:29092
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true