server:
  port: 9042

spring:
  application:
    name: order-query-service
  datasource:
    url: jdbc:postgresql://localhost:5433/asset
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  elasticsearch:
    rest:
      uris: http://localhost:9200
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db/migration
    enabled: false
    baseline-on-migrate: false