server:
  port: 9040

spring:
  application:
    name: order-command-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  kafka:
    bootstrap-servers: localhost:29092
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: false